### ISSUE TITLE
Add Hint That Some Functions Require A FRITZ!Box 7000

### ISSUE THREAD

**Issue by FlorianWendelborn** [andig/smartfritz#4]
I own a FRITZ!Box 3490 and thought the only difference is that I won't be able to use a landline phone. Apparently that's not true, since some of these API calls fail.

I think it'd be good to include a notice that most functions need a FRITZ!Box 7000.

**Comment by andig** [comment]
See 

> All functions have been tested on FritzOS 6.20/6.36 / FritzBox 7390. The WLAN functions may be less stable.

and

> AHA-HTTP-Interface document http://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AHA-HTTP-Interface.pdf
