### ISSUE TITLE
setGuestWlan Doesn't Work

### ISSUE THREAD

**Issue by FlorianWendelborn** [andig/smartfritz#5]
### Code

``` javascript
fritz.getSessionID(options.user, options.password, {
    host: options.host
}).then(sessionID => {

    console.log(sessionID);

    fritz.setGuestWlan(sessionID, true).then(data => {

        console.log(data);

        fritz.getGuestWlan(sessionID).then(data => {
            console.log(`data ${JSON.stringify(data)}`);
        });
    });
});
```
### Console Output

```
5c2something
{
    "ok": true,
    "validate": "apply"
}
data {"autoupdate":true,"activate_guest_access":false,"guest_ssid":"some_random_ssid","wpa_key":"some_random_key","push_service":false,"group_access":false,"untrusted":false,"user_isolation":false,"down_time_activ":true,"disconnect_guest_access":true,"sec_mode":"3","down_time_value":"120"}
```
### Expected Behavior

The third console.log should show `"activate_guest_access": true`.
### Versions

**FRITZ!Box**: 3490
**FRITZ!OS**: 6.51
**Node.js**: 4.2.1
**smartfritz-promise**: 0.5.0
**OS**: Raspbian Jessie on RPi 3
### Comments

ES6 transpiled via Babel.

I think this may be because the API apparently uses `true` and `false` instead of `on` and `off`. Otherwise, no idea why this won't work.

If you end up putting some more work into this call, it'd be nice to allow users to set a new Guest WLAN password too. I'd definitely use that.

**Comment by andig** [comment]
Unfortunately the wlan functions are hacky as there's no API available. Any fixes are welcome, otherwiese wontfix, sorry.

**Comment by FlorianWendelborn** [comment]
@andig I may consider writing a npm package myself then, are you aware of any resources/links that'd help me to do that? Since you worked for some time with FRITZ!APIs, you may have encountered some good links.

Also I think the issue should stay open until the API call is either removed, or fixed.

**Comment by andig** [comment]
> Since you worked for some time with FRITZ!APIs, you may have encountered some good links.

Not really- I'd use any one you like and start from there as template.

> Also I think the issue should stay open until the API call is either removed, or fixed.

It's really wontfix and documented. If AVM (feel free to call them) publishes an API I'd use that any second but I don't have time fixing something that can change any second (and already did a number of times...)

**Comment by andig** [comment]
With https://github.com/andig/smartfritz/commit/12915a6ffaf507e7f1de3299ca14348bb4fef62d this should finally be solved! Tested on FritzOS 6.51, FB 7390.

**Comment by andig** [comment]
> I have a kde (Vodafone) 6490 cable with version 6.50

@n3roGit could you please run this code and post the output:

```
var fritz = require('./smartfritz.js');

var options = {
    url: "<ip>"
};
var username = "<user>";
var password = "<password>";

fritz.getSessionID(username, password, options).then(function(sid) {
    console.log("SID: " + sid);

    // display switch information
    console.warn("get");
    fritz.getGuestWlan(sid, options).then(function(res) {
        console.log(res);

        console.warn("set on");
        fritz.setGuestWlan(sid, true, options).then(function(res) {
            console.log(res);

            console.warn("set off");
            fritz.setGuestWlan(sid, false, options).then(function(res) {
                console.log(res);
            });
        });
    });
});
```

For further debugging I would need access to the box. If you feel like it pm me the dns/username/password at `cpuidle@gmx.de` feel free to do so though I realize that that's a lot to ask...

**Comment by n3roGit** [comment]
@andig 
THX for fast reaction!
Whats to do to run this Script?

**Comment by andig** [comment]
For where you've installed smartfritz-promise just save it as e.g. `wlan.js` and then `node wlan.js`

**Comment by n3roGit** [comment]
/pimatic-app/node_modules/pimatic-fritz/node_modules/smartfritz-promise node guesttest.js
Unhandled rejection (<{"error":{},"options":{"url":"fritz.bo...>, no stack trace)

**Comment by andig** [comment]
@n3roGit anything inside the function can go wrong, starting with wrong uri or login data. I'll need to be able to access the box. If you want to risk it pm me at cpuidle@gmx.de.

**Comment by FlorianWendelborn** [comment]
Alternatively, just catch the promise rejection.

**Comment by andig** [comment]
> Alternatively, just catch the promise rejection.

What you're saying is "look whats wrong and fix all occurances". Absolutely, yes if skill permits! I just don't think we'll get this done with ping-pongig here

**Comment by FlorianWendelborn** [comment]
@andig I'm assuming that you're using some meaningful `reject()` errors. They may make spotting the error trivial.

EDIT: Whoops, forgot that GitHub changes the tab-through order of the buttons when commenting.

**Comment by andig** [comment]
Working for @n3roGit.
@dodekeract whats missing for you? The initial script you've posted should work with current smartfritz!

**Comment by FlorianWendelborn** [comment]
@andig nothing, in the meantime I wrote my own library to handle this, so I haven't tested this.
I was just noting, that you used promises  in your example, without `.catch()`ing the reject, leading to no errors shown.

**Comment by FlorianWendelborn** [comment]
Closing this as it seems to be resolved.
